name: Secrets Demo

on: [workflow_dispatch]

jobs:
  no-environment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.MY_REPO_SECRET }}"
      - run: echo "${{ secrets.MY_LOAD_TEST_SECRET }}"
  environment:
    runs-on: ubuntu-latest
    environment: Load-Test
    steps:
      - run: echo "${{ secrets.MY_REPO_SECRET }}"
      - run: echo "${{ secrets.MY_LOAD_TEST_SECRET }}"
